### ISSUE TITLE
We should open source this

### ISSUE THREAD

**Issue by JakeChampion** [BBC-archive/npmrc-switcher#3]
Once tests have been added and I refactor it as this is currently an initial attempt

**Comment by kenoir** [comment]
Don't see why not. I wouldn't necessarily wait until it's 'perfect' either.

Earlier we push the 'pubic' button the more likely it is it will end up open.

**Comment by JakeChampion** [comment]
Sounds good to me.

**Comment by kenoir** [comment]
Let me or @sthulb know when you're happy and we'll make the change.

**Comment by JakeChampion** [comment]
Now is as good a time as any I guess.

**Comment by kenoir** [comment]
Done. Probably a good idea to add a lit bit more info to the readme :)

**Comment by JakeChampion** [comment]
Just updating it now :)
