### ISSUE TITLE
Shell formatting

### ISSUE THREAD

**Issue by Integralist** [BBC-archive/npmrc-switcher#5]
https://github.com/BBC-News/npmrc-switcher/blob/master/lib/auto.sh

Shell formatting should be 2 spaces and not 8! :scream:

**Comment by JakeChampion** [comment]
I'm going to add the JSCS rules for the Javascript files, what could I use to check the style of the shell script?

**Comment by Integralist** [comment]
Shell scripting is a whole world I've not yet had the opportunity to properly understand so for now I'd suggest just writing scripts that are as simple and easy to understand as possible :-)

**Comment by JakeChampion** [comment]
Same here. I headed to the bash irc channel on freenode for help. I was recommended to overwrite the default cd command with a function, but I didn't think that was wise as I'm trying to make this reusable on multiple machines.

**Comment by JakeChampion** [comment]
landed in https://github.com/BBC-News/npmrc-switcher/commit/d81e4f10f75658004bef457e04998a52c0de4f0c
