### ISSUE TITLE
Multiple checks for home directory

### ISSUE THREAD

**Issue by Integralist** [BBC-archive/npmrc-switcher#6]
Why are you checking multiple paths for the home directory?

``` js
return process.env.HOME || process.env.HOMEPATH || process.env.USERPROFILE;
```

I would've thought `process.env.HOME` would be all you needed.

**Comment by JakeChampion** [comment]
I was thinking about making it work on Windows machines, but I don't actually have one to test it on.

**Comment by Integralist** [comment]
For a first stab I would say focus on getting it working the best it can on your primary environment. It'll make adding a new feature (such as Windows support) a lot easier then (rather than trying to refactor effectively two separate systems - one of them badly).

**Comment by JakeChampion** [comment]
That shall be the plan from here on out.

**Comment by JakeChampion** [comment]
landed in https://github.com/BBC-News/npmrc-switcher/commit/1f09aac8dd6b732318c58108330acb6cc8759c91
