### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by Integralist** [BBC-archive/npmrc-switcher#7]
Some minor changes I'd probably suggest making (not tested!)

I start with small refactorings: 
- renaming variables and functions so their intent is clearer
- moving code around so it reads more like a story: do a, then b, then c
- DRY out code
- look at code that appears a bit smelly (`if` statements are always a bit of a smell)

``` js
#! /usr/bin/env node

var fs     = require('fs');
var shell  = require('child_process').execFile;
var findup = require('findup-sync');

// Only check the value once
var baseDirectory = (function(){
    return process.env.HOME || process.env.HOMEPATH || process.env.USERPROFILE;
}());

var baseFilePath   = baseDirectory + '/.npmrc';
var baseBackupPath = baseDirectory + '/.npmrc.bak';
var nearestPath    = getPath();

if (nearestPath) {
    backupCurrent();
    copySourceToDestination(nearestPath, baseFilePath);
} else {
    returnToDefault();
}

function getPath() {
    var npmrcPath = findup('.npmrc');

    if (npmrcPath && npmrcPath !== baseFilePath) {
        return npmrcPath;
    }

    return null;
}

function renameFile(currentFileName, newFileName) {
    if(fs.existsSync(currentFileName)) {
        fs.renameSync(currentFileName, newFileName);

        if(fs.existsSync(currentFileName)) {
            throw new Error("Couldn't rename file");
        }
    }
}

function copySourceToDestination(source, destination) {
    shell('/bin/cp', [source, destination]);
}

function returnToDefault() {
    renameFile(baseBackupPath, baseFilePath)
}

function backupCurrent() {
    renameFile(baseFilePath, baseBackupPath)
}
```

There's more I could probably do but this was only a quick 5min review :-)

**Comment by JakeChampion** [comment]
Thanks for the review/refactoring. This reads a lot easier, I'll implement these changes in a PR now.

**Comment by Integralist** [comment]
Other things I would suggest...
- `npmrcPath && npmrcPath !== baseFilePath` should be inside a method with a descriptive name (as the expression is now quite complex)
- Ensure that you can scan the code and still understand what it does (that's one of the main things I start with - I scan the code and because I don't know anything about it, if I can't understand it then it needs to be refactored until I do understand it)
- I'd probably rename `baseFilePath` and `baseBackupPath` so they didn't have the `Path` at the end (no need for that and just makes the names harder to scan over)
- I'd probably rename `backupCurrent` and `returnToDefault` to be more descriptive of what they do (see how I took the `copyFile` method and changed it to be more descriptive so that the arguments passed through to it were clearer `copySourceToDestination`)
- I'd probably rename `nearestPath` to `nearestFile` so it stays consistent with the other renamings I suggested above

**Comment by JakeChampion** [comment]
https://github.com/BBC-News/npmrc-switcher/pull/8

**Comment by JakeChampion** [comment]
landed in https://github.com/BBC-News/npmrc-switcher/commit/bd83ca78f4c6d86870a90f643b5ae440bd9494a1
